######### Registro do usuário 
POST http://127.0.0.1:3333/register HTTP/1.1
Content-Type: application/json

{
"name": "Alice Martins",
"email": "aliceluciamartinsdeoliveira@gmail.com",
"password": "123456789"
}

######### Autenticação do usuário 
POST http://127.0.0.1:3333/login HTTP/1.1 n
Content-Type: application/json

{
"email": "lazarodu@gmail.com",
 "password": "1234"
}